services:
  master:
    build: ./simulators/master
    platform: linux/amd64
    container_name: master
    restart: no

  capture:
    build: ./capture
    platform: linux/amd64
    container_name: capture
    restart: "no"
    network_mode: "service:master"
    cap_add:
      - "NET_ADMIN"
      - "NET_RAW"

  # Master's side-car for monitoring traffic outside docker network
  #tcpdump:
  #  image: nicolaka/netshoot
  #  network_mode: "service:master"
  #  command: tcpdump -U -i eth0 -w /captures/dnp3.pcap tcp port 20000
  #  volumes:
  #    - ./pcaps:/captures

  outstation-1:
    build: ./simulators/outstation
    platform: linux/amd64
    container_name: outstation-1
    restart: no
    ports:
      - "20001:20000"
    environment:
        TURBINE_DATA: "turbines/turbine_1.csv"

  outstation-2:
    build: ./simulators/outstation
    platform: linux/amd64
    container_name: outstation-2
    restart: no
    ports:
      - "20002:20000"
    environment:
      TURBINE_DATA: "turbines/turbine_2.csv"

  outstation-3:
    build: ./simulators/outstation
    platform: linux/amd64
    container_name: outstation-3
    restart: no
    ports:
      - "20003:20000"
    environment:
      TURBINE_DATA: "turbines/turbine_3.csv"

